### ISSUE TITLE
Higher-poly and interaction transparency for Hedeby chest

### ISSUE THREAD

**Issue by BluebsTopCat** [Virtual-Viking-Longship/VVLP-Hedeby-Chest#58]

**Comment by BluebsTopCat** [comment]
I need a few more models for this to work- there exists no photogrammetry for the shears, for example.

**Comment by apjmason** [comment]
I can work on more photogrammetry models tomorrow

**Comment by apjmason** [comment]
In the meantime, [this is the document](https://docs.google.com/file/d/1Xs5CzEq0dvAg7Ns5WZXTdOpFM4ZnTQIv/edit?usp=docslist_api&filetype=msword) with all the objects we scanned at Hedeby, which includes the dimensions for each so you can make sure the low poly models are correctly sized.

**Comment by BluebsTopCat** [comment]
Will do, thank you!
